-- MySQL Script generated by MySQL Workbench
-- Wednesday 16 February 2022 09:40:12 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dataminr
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dataminr` ;

-- -----------------------------------------------------
-- Schema dataminr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataminr` DEFAULT CHARACTER SET utf8 ;
USE `dataminr` ;

-- -----------------------------------------------------
-- Table `dataminr`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataminr`.`tasks` ;

CREATE TABLE IF NOT EXISTS `dataminr`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataminr`.`task_lists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataminr`.`task_lists` ;

CREATE TABLE IF NOT EXISTS `dataminr`.`task_lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataminr`.`task_lists_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataminr`.`task_lists_tasks` ;

CREATE TABLE IF NOT EXISTS `dataminr`.`task_lists_tasks` (
  `tasks_id` INT NOT NULL,
  `task_lists_id` INT NOT NULL,
  PRIMARY KEY (`tasks_id`, `task_lists_id`),
  INDEX `fk_tasks_has_task_lists_task_lists1_idx` (`task_lists_id` ASC) VISIBLE,
  INDEX `fk_tasks_has_task_lists_tasks_idx` (`tasks_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_has_task_lists_tasks`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `dataminr`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_has_task_lists_task_lists1`
    FOREIGN KEY (`task_lists_id`)
    REFERENCES `dataminr`.`task_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'root';


-- MySQL dump 10.13  Distrib 8.0.23, for Linux (x86_64)
--
-- Host: localhost    Database: dataminr
-- ------------------------------------------------------
-- Server version	8.0.28

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `task_lists`
--

DROP TABLE IF EXISTS `task_lists`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `task_lists` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `task_lists`
--

LOCK TABLES `task_lists` WRITE;
/*!40000 ALTER TABLE `task_lists` DISABLE KEYS */;
INSERT INTO `task_lists` VALUES (3,'Mobile App Release','2022-02-17 15:33:22','2022-02-17 15:33:22'),(4,'Website Release','2022-02-17 15:33:45','2022-02-17 15:33:45');
/*!40000 ALTER TABLE `task_lists` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `task_lists_tasks`
--

DROP TABLE IF EXISTS `task_lists_tasks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `task_lists_tasks` (
  `tasks_id` int NOT NULL,
  `task_lists_id` int NOT NULL,
  PRIMARY KEY (`tasks_id`,`task_lists_id`),
  KEY `fk_tasks_has_task_lists_task_lists1_idx` (`task_lists_id`),
  KEY `fk_tasks_has_task_lists_tasks_idx` (`tasks_id`),
  CONSTRAINT `fk_tasks_has_task_lists_task_lists1` FOREIGN KEY (`task_lists_id`) REFERENCES `task_lists` (`id`),
  CONSTRAINT `fk_tasks_has_task_lists_tasks` FOREIGN KEY (`tasks_id`) REFERENCES `tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `task_lists_tasks`
--

LOCK TABLES `task_lists_tasks` WRITE;
/*!40000 ALTER TABLE `task_lists_tasks` DISABLE KEYS */;
INSERT INTO `task_lists_tasks` VALUES (2,3),(3,3),(4,3),(5,4);
/*!40000 ALTER TABLE `task_lists_tasks` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `tasks`
--

DROP TABLE IF EXISTS `tasks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tasks` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `description` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `tasks`
--

LOCK TABLES `tasks` WRITE;
/*!40000 ALTER TABLE `tasks` DISABLE KEYS */;
INSERT INTO `tasks` VALUES (2,'App Design Mockup','App design wireframes should be designed and reviewed','2022-02-17 15:34:22','2022-02-17 15:34:22'),(3,'App UI','App UI should be designed, reviewed and approved','2022-02-17 15:34:50','2022-02-17 15:34:50'),(4,'App Development','App development should be complete by xxxx','2022-02-17 15:35:28','2022-02-17 15:35:28'),(5,'Web Development','App development should be complete by xxxx','2022-02-17 15:35:34','2022-02-17 15:35:34');
/*!40000 ALTER TABLE `tasks` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2022-02-17 21:12:15
